### ISSUE TITLE
[Suggestion] - First ember view, Paper-nav-container enhancement

### ISSUE THREAD

**Issue by ssirowy** [miguelcobain/ember-paper#210]
I had used the [template defined here](http://miguelcobain.github.io/ember-paper/#/sidenav)  as a great starting point for a new app I'm building. 

With just this example, I noticed my content caused the entire toolbar to scroll off screen.  This was not happening in the sample app. 

The reason the sample template scrolled the toolbar off the screen was the absence of 
``` css
.site-nav-container, body>div.ember-view:first-of-type {
    width: 100%;
    height: 100%;
}
```

and 
``` html
{{#paper-nav-container class='site-nav-container'}}
```
`site-nav-container` defined as a class on `#paper-nav-container`

This seems like such a common pattern (fixed toolbar) that it might be nice to include this as the sensible default.

**Comment by jamesdixon** [comment]
@ssirowy just as a heads up, I ran into issues with that particular piece of CSS, specifically the `:first-of-type` selector. Unfortunately, it doesn't to work when applied to a class, such as `.ember-view`. It _appears_ to work in the dummy app because it happens to be the first `div`, but if you have any other addons that add a `div` right after the `body` tag and before the `div` created by your application, it will fail to work. Ideally, you'd add a class or ID to the root `ember-view` and then target that. However, I haven't found a way to do that. In the meantime, my workaround is to target the class specifically although I'm not sure how stable the workaround will be given that other addons may add `ember-view` only divs to the root:

```css
body > div[class='ember-view'] {
    width: 100%;
    height: 100%;
}
```

cc: @miguelcobain

**Comment by ssirowy** [comment]
>   but if you have any other addons that add a div right after the body tag and before the div created by your application, it will fail to work.

Is this a common practice?

**Comment by jamesdixon** [comment]
It appears to be. For example, I'm using [ember-power-select](https://github.com/cibernox/ember-power-select) and it adds a wormhole right after the body tag, which appears before the ember-view generated by the application. See this as well: https://github.com/miguelcobain/ember-paper/issues/214

**Comment by mike1o1** [comment]
The ember-inspector also seems to be inconsistent on where or when it adds its overlay elements, which can also mess up the selector.

In my apps, I've ended up just using the [`ember-legacy-views`](https://github.com/emberjs/ember-legacy-views) addon, and the proper attributes to my `ApplicationView`.

```js
import Ember from 'ember';

var ApplicationView = Ember.View.extend({
  attributeBindings: ['flex:flex'],
  flex: true,
  'flex-layout': 'row'
});

export default ApplicationView;
```

In my index.html, I also add `[layout=row]` to the body element. It's a pain to have to do this on every app, but it's a one time thing until routable components land so we can probably add attributes to the main view.

**Comment by joukevandermaas** [comment]
We use this which works:

```scss
// needed to make the sidebar 100% height
body > .ember-view {
  width: 100%;
  height: 100%
}

// only the app template should get the height,
// other ember views should not
body > .ember-view ~ .ember-view {
    height: auto;
    width: auto;
}
```

the `~` operator selects siblings so `a ~ b` matches `b` following a sibling `a`.
