### ISSUE TITLE
paper-icon spin CSS is missing.

### ISSUE THREAD

**Issue by DanChadwick** [miguelcobain/ember-paper#296]
Since the conversion to using angular source, I don't see the md-spin and md-reverse-spin CSS. The class is correctly rendered in the component; it's just a missing CSS issue.

What seems to be missing from the previous hand-built stylesheet:
```css
// Icon spinners
  .md-spin {
   animation: md-spin 1.5s infinite linear;
}
 
.md-spin-reverse {
  animation: md-spin-reverse 1.5s infinite linear;
}

// Spin
@keyframes md-spin {
  0% {
    transform: rotate(0deg);
   }
  100% {
    transform: rotate(359deg);
  }
}

// Spin Reverse
@keyframes md-spin-reverse {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(-359deg);
  }
}
```
