### ISSUE TITLE
Support for icon sizes in paper-icon

### ISSUE THREAD

**Issue by lefteyecc-pu** [miguelcobain/ember-paper#358]
Hey Guys,

Just a quick note. You do not currently have support for icon sizes in paper-icon. Specifically in legacy ember-paper you had:

```css
// Icon sizes
.md-lg {
    font-size: 1.5em;
}

.md-sm {
    font-size: 1em;
}

.md-2x {
    font-size: 2em;
}

.md-3x {
    font-size: 3em;
}

.md-4x {
    font-size: 4em;
}

.md-5x {
    font-size: 5em;
}
```

This isn't urgent as I just coppied this CSS to my app stylesheet.
