### ISSUE TITLE
Overwriting CSS

### ISSUE THREAD

**Issue by John0x** [miguelcobain/ember-paper#607]
Why do I have to use the !important flag to overwrite most of the css attributes?
For example the following does not work:

````scss
@import "ember-paper";

md-toolbar {
  color: green;
}
````

Once I add !important to the color it works. What is the intended way of overwriting css styles?

**Comment by miguelcobain** [comment]
What happens if you import after the override?

**Comment by John0x** [comment]
@miguelcobain it doesn't change a thing. The same behaviour.

**Comment by miguelcobain** [comment]
@John0x the reason is because `md-toolbar` is a more generic selector than the default one: https://github.com/angular/material/blob/master/src/components/toolbar/toolbar-theme.scss#L1

So, the more specific wins.

If you don't want to change the global primary contrast variable and only override toolbar color, you should add a class to your toolbar and then

```css
md-toolbar.md-default-theme.your-css-class {
  color: green;
}
```

We do that on the demo app here: https://github.com/miguelcobain/ember-paper/blob/master/tests/dummy/app/styles/demo.scss#L174
