### ISSUE TITLE
Is possible to set a custom color to paper-icon?

### ISSUE THREAD

**Issue by manuelsalvatori** [miguelcobain/ember-paper#658]
paper-icon supports colors based on primary warn and so on, I need to set a custom color for certain icons is it possible to do it via component property?

For example
{{paper-icon icon color=desiredColor}}

**Comment by zlodes** [comment]
@manuelsalvatori, you may use CSS.

```css
.green {
    color: #00ff00;
}
```
```
{{paper-icon icon class="green"}}
```

**Comment by miguelcobain** [comment]
You need a different selector though:

```css
md-icon.md-default-theme.green {
  color: #00ff00;
}
```

You can always use `!important` as well.
