### ISSUE TITLE
Angular "color" in compiled CSS

### ISSUE THREAD

**Issue by panthony** [miguelcobain/ember-paper#800]
I noticed that the generated CSS is containing some angular "color" variables in compiled css. 

From the CSS of the dummy app:

```css
md-content,md-content.md-default-theme {
    color: rgba(0,0,0,.87);
    background-color: "A100"
}
```

```css
.md-subheader,.md-subheader.md-default-theme {
    color: rgba(0,0,0,.23);
    background-color: "A100"
}
```

**Comment by essmd** [comment]
Same here!

```css
md-content.md-default-theme, md-content {
    color: rgba(0, 0, 0, 0.87);
    background-color: "A100";
}
```
