### ISSUE TITLE
paper-menu-item: css issue when scrollable with `dense=true`

### ISSUE THREAD

**Issue by panthony** [miguelcobain/ember-paper#922]
When you use the `dense:true` option and the menu's content is scrollable then there is a display issue:

![capture d ecran 2018-05-11 a 08 30 16](https://user-images.githubusercontent.com/230462/39910017-9b8c46b2-54f5-11e8-98a8-e249ed2d63af.png)

The `md-menu-item` does not respect the height of 32px.

Its default css is

```css
md-menu-content.md-dense md-menu-item {
    height: 32px;
    min-height: 0px;
}
```

Setting `min-height` to `32px` fixes the issue.

Should it be patched in `ember-paper`?
